#!/usr/bin/env node
/**
 * Generate the tag -> risk-domain lookup consumed by both halves of the dashboard.
 *
 * Source of truth is `tag_map.yaml` in the playwright-automation repo. This script
 * compiles it into two artifacts so neither side has to parse YAML at runtime:
 *
 *   src/lib/domains.generated.ts   imported by the SPA
 *   ci/domains.generated.json      read by ci/qa-summary.mjs
 *
 * Regenerate whenever tag_map.yaml changes:
 *
 *   npm run gen:domains -- --tag-map ../playwright-automation/tag_map.yaml
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { parseArgs } from 'node:util';
import yaml from 'js-yaml';

// Buckets that describe *how* a test is written rather than *what business area*
// it covers. A scenario tagged @pagination @invoices belongs to invoices; the
// generic bucket only wins when nothing more specific matched. Higher number =
// more generic = picked later when choosing a scenario's primary domain.
const GENERICITY = {
  tables: 3,
  admin: 2,
  documents: 2,
  exceptions: 2,
  routing: 2,
};

// Human-facing labels. Anything absent falls back to a title-cased slug.
const LABELS = {
  fsc: 'FSC',
  api: 'API',
  uv: 'Unified View',
  unified_view: 'Unified View',
  order_billing: 'Order Billing',
  order_booking: 'Order Booking',
  shipment_leg_management: 'Shipment Leg Mgmt',
  delivery_order: 'Delivery Order',
  lane_rates: 'Lane Rates',
};

const stripAt = (tag) => String(tag).replace(/^@/, '').toLowerCase();

function labelFor(slug) {
  if (LABELS[slug]) return LABELS[slug];
  return slug
    .replace(/[_-]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function build(tagMapPath) {
  const raw = yaml.load(readFileSync(tagMapPath, 'utf8')) ?? {};
  const domainsRaw = raw.domains ?? {};

  const domains = [];
  const tagToDomains = {};

  Object.entries(domainsRaw).forEach(([slug, cfg], order) => {
    const tags = (cfg?.tags ?? []).map(stripAt);
    const description = String(cfg?.description ?? '').split(/\s+/).join(' ').trim();

    domains.push({
      slug,
      label: labelFor(slug),
      description,
      tags,
      order,
      genericity: GENERICITY[slug] ?? 1,
    });

    for (const tag of tags) {
      (tagToDomains[tag] ??= []).push(slug);
    }
  });

  // Tags that exist for traceability rather than to describe an area: legacy case
  // ids, Linear/bug refs, ad-hoc runner tags. tag_map declares these as regexes
  // under `non_routing`, so the dashboard filters them out of the tag breakdown
  // using tag_map's own patterns instead of guessing.
  const nonRouting = [];
  for (const entry of Object.values(raw.non_routing ?? {})) {
    for (const pattern of entry?.patterns ?? [entry?.pattern]) {
      // Stored unanchored-at-the-@ so they can be tested against bare tag names.
      if (pattern) nonRouting.push(String(pattern).replace('^@', '^'));
    }
  }

  return {
    version: raw.version ?? 1,
    source: 'tag_map.yaml',
    domains,
    tagToDomains: Object.fromEntries(Object.entries(tagToDomains).sort(([a], [b]) => a.localeCompare(b))),
    layers: (raw.layers ?? []).map(stripAt),
    excludeAlways: (raw.exclude_always ?? []).map(stripAt),
    scopes: Object.keys(raw.scopes ?? {}),
    authRoles: (raw.auth_roles ?? []).map(stripAt),
    nonRoutingPatterns: nonRouting,
  };
}

function emitTs(data) {
  return `// AUTO-GENERATED by scripts/gen-domains.mjs — do not edit by hand.
// Source: playwright-automation/${data.source} (tag_map version ${data.version})
//
// Regenerate with:
//   npm run gen:domains -- --tag-map ../playwright-automation/tag_map.yaml

export interface DomainDef {
  slug: string;
  label: string;
  description: string;
  tags: string[];
  /** Declaration order in tag_map.yaml — the tie-breaker for primary-domain choice. */
  order: number;
  /** 1 = specific business area, higher = generic bucket picked only as a last resort. */
  genericity: number;
}

export const DOMAINS: DomainDef[] = ${JSON.stringify(data.domains, null, 2)};

/** Lowercased, unprefixed behave tag -> every domain that claims it. */
export const TAG_TO_DOMAINS: Record<string, string[]> = ${JSON.stringify(data.tagToDomains, null, 2)};

export const LAYER_TAGS: string[] = ${JSON.stringify(data.layers)};

/** Scope selectors (@smoke, @regression) - they describe *when* a test runs, not what it covers. */
export const SCOPE_TAGS: string[] = ${JSON.stringify(data.scopes)};

/** Always-excluded gates (@wip, @bug, @skip …). */
export const EXCLUDE_TAGS: string[] = ${JSON.stringify(data.excludeAlways)};

/** Auth-role selectors (@auth.admin …) - they say who logs in, not what is covered. */
export const AUTH_ROLE_TAGS: string[] = ${JSON.stringify(data.authRoles)};

/**
 * Tags kept only for traceability — case ids, ticket refs, ad-hoc runner tags.
 * Patterns come straight from tag_map's non_routing section.
 */
export const NON_ROUTING_PATTERNS: string[] = ${JSON.stringify(data.nonRoutingPatterns)};

export const DOMAIN_BY_SLUG: Record<string, DomainDef> = Object.fromEntries(
  DOMAINS.map((d) => [d.slug, d]),
);

/** Bucket for scenarios whose tags match no domain in tag_map.yaml. */
export const UNMAPPED_DOMAIN = 'unmapped';

export function labelForDomain(slug: string): string {
  if (slug === UNMAPPED_DOMAIN) return 'Unmapped';
  return DOMAIN_BY_SLUG[slug]?.label ?? slug;
}
`;
}

const { values } = parseArgs({
  options: {
    'tag-map': { type: 'string', default: '../playwright-automation/tag_map.yaml' },
    'ts-out': { type: 'string', default: 'src/lib/domains.generated.ts' },
    'json-out': { type: 'string', default: 'ci/domains.generated.json' },
  },
});

const tagMapPath = resolve(values['tag-map']);
let data;
try {
  data = build(tagMapPath);
} catch (err) {
  console.error(`Failed to read tag_map.yaml at ${tagMapPath}\n${err.message}`);
  process.exit(1);
}

for (const [outPath, contents] of [
  [values['ts-out'], emitTs(data)],
  [values['json-out'], `${JSON.stringify(data, null, 2)}\n`],
]) {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, contents);
  console.log(`wrote ${outPath}`);
}

console.log(`${data.domains.length} domains, ${Object.keys(data.tagToDomains).length} tags`);
